# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.wow_api:
        class: AppBundle\Api\WoWApi
        arguments: ['%app.wow_api.blizzard_key%', '%app.wow_api.blizzard_secret%']
    app.character_manager:
        class: AppBundle\Utils\CharacterManager
        arguments: ['@app.wow_api', '%dfblizz%']
    app.character_creator:
        class: AppBundle\Utils\CharacterCreator
        arguments: ['@app.character_manager', '%dfblizz%']
